### ISSUE TITLE
[proposal] Allow the ability to add custom udev rules to the hostOS

### ISSUE THREAD

**Issue by shaunmulligan** [balena-os/balena-os#160]
In some cases (working with cellular modems, etc) it is useful to be able to define some kind of custome udev rule which runs at startup before the containers start up. It would be great if people had the ability to add custome udev rules to the boot partition like they do for system connections and have the hostOS apply these at startup. 

I would like to use this issue as a place to discuss the use cases for this type of feature and possible implementation details.

**Comment by agherzan** [comment]
@shaunmulligan can you please link the spec ?

**Comment by shaunmulligan** [comment]
I believe the usecase are
1.) if one has custom usb_modeswitch settings you need to run in order to bring up a GSM modem correctly
2.) In the case where you have multiple containers (c1 and c2) and each container needs to be assigned to a specific usb device and the containers are not priviledged

Additionally, @linux4kix stated that many core udev rules are written such that a failed match will go to a generic catchall rule, or bail out. I think two udev daemons would race and compete on device discovery

**Comment by shaunmulligan** [comment]
there is also the case where you want to have a usb serial device or something that is always given the same name, so you can have an unpriviledged container that is run with `docker run <name> --device=/dev/ttyUSB0`

**Comment by agherzan** [comment]
@petrosagg what do you think about these?

**Comment by shaunmulligan** [comment]
Additional info on the usb_modeswitch usecase from @alexissusset on gitter:
> I had to create a rule in `/etc/usb_modeswitch.d/`

>basically trying to run this command:
```
usb_modeswitch -W -I -v 12d1 -p 1f01 -V 12d1 -P 1001 -M "55534243123456780000000000000011060000000000000000000000000000"
```
and so edited `/etc/usb_modeswitch.d/12d1\:1f01`

**Comment by alexandrosm** [comment]
can we get the users to directly contribute here?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by shaunmulligan** [comment]
@alexandrosm yeah, I want that too. I have pointed to this issue a couple times, I guess this is another place gitter sometimes cannibalises discussion.

**Comment by blaines** [comment]
These are capabilities we would use if included in resin.

**Comment by halebr** [comment]
Blaine not able to comment on this ticket so adding this from him: 

"On our TX2 boards we want to have the 2 swift serial ports enumerate as /dev/swift1 and /dev/swift2 and the 6 multitech dragonfly ports as /dev/dragonfly1 through 6. "

**Comment by mhoejgaard** [comment]
We would really appreciate this feature as we are using it in Ubuntu Mate on our development RPI3's but have not found a way to do it with resin yet.

**Comment by agherzan** [comment]
@mhoejgaard Could you please describe your use-case in more details?

**Comment by brettdaman** [comment]
I have a use case where I could use this. I have 2 identical motor controller boards as USB devices. I use udev to make sure that I control the correct board for each movement. But its not scalable to multiple devices. since I need to enter the unique serial numbers in the udev files before I copie them in the dockerfile.

**Comment by dgarcoe** [comment]
Hi, for me it would me nice also unless there are other ways to do this. I have some serial device that appears as /dev/ttyACM0 when connecting it for first time but then, if the device is restarted it shows as /dev/ttyACM1. It would be nice to be able to define a static name such as /dev/serialdev so I always know where to look for it.

**Comment by mevatron** [comment]
@agherzan Our company would also make use of this feature as we have several different devices that communicate over FTDI USB to serial converters. We use custom FTDI serial numbers to distinguish between devices and automatically make /dev mappings.

**Comment by sonofaforester** [comment]
This is important to us also

**Comment by martenjacobs** [comment]
I'd also like to be able to do this to map the port numbers of multiport FTDI USB-to-serial converters

**Comment by samuelbacaner** [comment]
This issue can probably be closed because @ZubairLK's [PR](https://github.com/balena-os/meta-balena/pull/1206) was merged a while ago. Unless that solution didn't cover everything above?

**Comment by brettdaman** [comment]
It worked for me. It can be closed

**Comment by ZubairLK** [comment]
Thanks. Closing this now.
