### ISSUE TITLE
Support for CTI ORBITTY CARRIER FOR NVIDIA JETSON TX2

### ISSUE THREAD

**Issue by shaunmulligan** [balena-os/balena-os#394]
We would like to support the [CTI ORBITTY CARRIER FOR NVIDIA JETSON TX2](http://connecttech.com/product/orbitty-carrier-for-nvidia-jetson-tx2-tx1/) on resin.io.

From the looks of it, it will require changing the default DTB to the CTI custom one. They also have an additionally BSP layer referenced [here](http://connecttech.com/resource-center/cti-l4t-nvidia-jetson-board-support-package-release-notes/) that provides support for PWM control of the CPU fan and a perhaps a few other things.

Proposed Plan for this:
* Get one of the CTI Orbitty carrier boards from [here](http://www.wdlsystems.com/Computer-on-Module/Carrier-Boards/CTI-Orbitty-Carrier-for-NVIDIA-Jetson-TX1.html)
* Create a new device type called something like `CTI Orbitty for TX2`
* When the hostApps feature is released we will work on migrating this back into the regular Jetson TX2 device type.

**Comment by agherzan** [comment]
Sounds like a good plan.

**Comment by shaunmulligan** [comment]
@telphan we can close this right? since we ended up adding the SKX2 device type?

**Comment by pastawoua** [comment]
@shaunmulligan what's the SKX2? is that custom carrier board?

**Comment by shaunmulligan** [comment]
@pastawoua yes its a custom carrier board produced by connectTech and similar to the [CTI ORBITTY CARRIER FOR NVIDIA JETSON TX2](http://connecttech.com/product/orbitty-carrier-for-nvidia-jetson-tx2-tx1/)

**Comment by pastawoua** [comment]
Thanks Shaun, I’ve been in touch with connecTech about customising one of their boards too, good to know it’s supported by resinOS.

**Comment by telphan** [comment]
@shaunmulligan The SKX2 device type is in a precarious situation now (i.e. we will remove it soon).

**Comment by pastawoua** [comment]
Quick question on this one, is the orbitty supported by default with resinOS at the moment, or would I need to build my own image?

**Comment by telphan** [comment]
We officially only support the Nvidia devkit at the moment. 
We will have a more general solution here to allow user to configure any carrierboard with our TX2 image, but that plan is yet to start.

**Comment by LorenzMeier** [comment]
@telphan The official carrier board is not really workable (too large for any real device) and currently a blocker. Is there a quick way to support one of the CTI boards?

**Comment by telphan** [comment]
@LorenzMeier we can follow the initial plan outlined here, if there is a real demand for one of the CTI boards.

**Comment by alan707** [comment]
@shaunmulligan @telphan would be incredibly grateful if we can include the Orbitty CTI board as an additional module.  We are going to ramp up production and considering resin.io as our IOT management/provisioning tool.  Is the Tx2i supported by virtue of supporting Tx2?

**Comment by alexandrosm** [comment]
Hi all, just as an update to the topic, we're currently working on supporting the CTI Orbitty carrier board for the TX2. 

@alan707 we haven't tested the TX2i (as far as I know) but even if it doesn't work out of the box, we're always open to making modifications to expand support, or if the board is really different, building out custom device support for customers.

**Comment by alan707** [comment]
@alexandrosm, thanks so much! When I tried inserting a resin.io flashed MicroSD on a Tx2i with Orbitty carrier it connected briefly over ethernet but then crashed to the point I had to reflash with Linux for Tegra again. Does the resin.io image on the SD card write to the emmc (non-volatile memory) in the Tx2i?

**Comment by alan707** [comment]
Oh, and forgot to ask, what is the estimated timeframe for having Orbitty carrier support?

**Comment by alan707** [comment]
@alexandrosm one of the nice things about the Orbitty/Tx2i is that is can be placed in `USB mode` which allows to connect directly running `screen /dev/ttyACM0`.

Additionally it would be very cool if when you put the Tx2i in recovery mode, `Etcher` recognizes is at as removable/flashable device and burns image directly to 30GB internal SSD memory that
comes native with the Tx2i. 

The goal here is to avoid the extra step of flashing the Tegra for Linux image first to Tx2i, then burning the resin.io image to MicroSD card.

**Comment by telphan** [comment]
@alan707 Hi, let me answer your questions in order. The tx2i is essentially a tx2, but from my experience with Nvidia they probably changed the layout of the partition table which means that once you have flashed the internal emmc with a TX2 image (yes we flash resinOS on the internal emmc) the board will not survive a reboot (it would require recovery mode flashing). 

The support for the Orbitty boards will be out very soon, I just need to find a bit of time to take care of it. 

I didn’t know that the Tx2i exposes the internal storage over the USB interface when in recovery mode, it means that adding support to flash the tx2i using etcher is essentially trivial. 
The tx2 is also on its way to support this mechanism, but due to some issue with one of the node dependencies for this project I had to pause progress on this.
But until that small issue is fixed I have created a tool (https://github.com/resin-os/jetson-flash) which uses the Nvidia tools to flash resinOS over USB the same way you are flashing Linux for Tegra.

**Comment by alan707** [comment]
@telphan @alexandrosm Any chance we can have ResinOS support for Tx2i and Orbitty board all in one ResinOS image?

**Comment by Jaeyoung-Lim** [comment]
@cakoolen works fine for me on the cti orbitty with tx2

**Comment by agherzan** [comment]
CC @floion

**Comment by thgreasi** [comment]
@shaunmulligan @floion @acostach should we close this?
I see that we already have a `CTI Orbitty TX2` device type on balena-cloud.

**Comment by drjasonharrison** [comment]
You can close this. I believe that I was able to get balena working on CTI ORBITTY Carrier and Jetson TX2

**Comment by drjasonharrison** [comment]
Unfortunately I'm no longer working on that project
