### ISSUE TITLE
Add proper instructions for Balena Fin

### ISSUE THREAD

**Issue by thgreasi** [balena-os/balena-os#487]
The getting started docs should be updated to describe the setup process for Balena FIn (atm using the default) and reflect what's in resin docs (which are currently empty).
See: #486 
See: https://docs.resinstaging.io/learn/getting-started/fincm3/nodejs/#adding-your-first-device

**Comment by lurch** [comment]
Looking at https://www.balena.io/docs/learn/getting-started/fincm3/nodejs/ it seems this has been done?

**Comment by thgreasi** [comment]
Once again @lurch you are right, thanks for the heads up :+1:
