### ISSUE TITLE
Enabling persistent logging sometimes eventually fills up the state partition

### ISSUE THREAD

**Issue by CameronDiver** [balena-os/balena-os#529]
We've seen this a couple of times, the fix being to remove the journal file and re-initialise the supervisor (if it broke).

Persistent logging is supposed to cut off after a certain size (8mb I believe) but we've seen cases of it taking all available state partition storage.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hoc3)

**Comment by alexandrosm** [comment]
@CameronDiver why not have it do sth like a circular buffer or sth.

**Comment by CameronDiver** [comment]
cc @ZubairLK as he is the one looking into this, I just made the issue to track it.

**Comment by ZubairLK** [comment]
Tracking this issue in meta-balena
