### ISSUE TITLE
Override lock

### ISSUE THREAD

**Issue by balenaio** [balena-os/balena-os#530]
# Description 
Test **locking updates** meaning that the balena supervisor will not be able to kill your application until you override the command.

# Steps to reproduce issue 
# 1. 
Push app to the device
`$ git clone https://github.com/balena-io-playground/balena-updates-lock`
`$ cd balena-updates-lock`
`$ git remote add balena YYY`   (copy the link from the application's dashboard)
`$ git push balena`

# 2. 
Push another application
`$ git clone https://github.com/resin-io-projects/simple-server-python`
`$ cd simple-server-python`
`$ git remote add balena YYY`   (copy the link from the application's dashboard)
`$ git push balena`

# 3.
Enable lock override in dashboard

# Expected result 
# 1. 
First application should be downloaded and installed, creating a lockfile i.e. "/tmp/balena/updates.lock"
Second application should be downloaded but **not** installed
After enabling lock override, the new application should be installed and run correctly
There should be **no** lockfile in /tmp/balena

# 2. Cleanup:
Disable lock override

# Actual result 
Second application is downloaded and installed on step 2, which shouldn't happen according to test steps.

13.03.19 13:23:44 (+0200) Started service 'main sha256:0fe3e601a913c7069af134ea964e68f805ca37ba1f0442dfcfa3523bc2c9d883'
13.03.19 13:23:46 (+0200)  main  Idling & locked: 1
13.03.19 13:25:48 (+0200) Downloading delta for image 'registry2.balena-cloud.com/v2/17105b6e9adbdbd352800eb3b3a60166@sha256:f8e9b88c55244658fe497a4957db8c1ea5cc272fce0501e0974801f4b4cce9b0'
13.03.19 13:26:09 (+0200) Delta still processing remotely. Will retry...
13.03.19 13:26:10 (+0200) Downloading delta for image 'registry2.balena-cloud.com/v2/17105b6e9adbdbd352800eb3b3a60166@sha256:f8e9b88c55244658fe497a4957db8c1ea5cc272fce0501e0974801f4b4cce9b0'
13.03.19 13:26:17 (+0200) Delta still processing remotely. Will retry...
13.03.19 13:26:18 (+0200) Downloading delta for image 'registry2.balena-cloud.com/v2/17105b6e9adbdbd352800eb3b3a60166@sha256:f8e9b88c55244658fe497a4957db8c1ea5cc272fce0501e0974801f4b4cce9b0'
13.03.19 13:26:24 (+0200) Delta still processing remotely. Will retry...
13.03.19 13:26:25 (+0200) Downloading delta for image 'registry2.balena-cloud.com/v2/17105b6e9adbdbd352800eb3b3a60166@sha256:f8e9b88c55244658fe497a4957db8c1ea5cc272fce0501e0974801f4b4cce9b0'
13.03.19 13:26:45 (+0200) Delta still processing remotely. Will retry...
13.03.19 13:26:46 (+0200) Downloading delta for image 'registry2.balena-cloud.com/v2/17105b6e9adbdbd352800eb3b3a60166@sha256:f8e9b88c55244658fe497a4957db8c1ea5cc272fce0501e0974801f4b4cce9b0'
13.03.19 13:27:05 (+0200) Delta still processing remotely. Will retry...
13.03.19 13:27:06 (+0200) Downloading delta for image 'registry2.balena-cloud.com/v2/17105b6e9adbdbd352800eb3b3a60166@sha256:f8e9b88c55244658fe497a4957db8c1ea5cc272fce0501e0974801f4b4cce9b0'
13.03.19 13:28:02 (+0200) Downloaded image 'registry2.balena-cloud.com/v2/17105b6e9adbdbd352800eb3b3a60166@sha256:f8e9b88c55244658fe497a4957db8c1ea5cc272fce0501e0974801f4b4cce9b0'
13.03.19 13:28:03 (+0200) Killing service 'main sha256:0fe3e601a913c7069af134ea964e68f805ca37ba1f0442dfcfa3523bc2c9d883'
13.03.19 13:28:06 (+0200) Service exited 'main sha256:0fe3e601a913c7069af134ea964e68f805ca37ba1f0442dfcfa3523bc2c9d883'
13.03.19 13:28:07 (+0200) Killed service 'main sha256:0fe3e601a913c7069af134ea964e68f805ca37ba1f0442dfcfa3523bc2c9d883'
13.03.19 13:28:08 (+0200) Deleting image 'registry2.balena-cloud.com/v2/1ec8f8943bc307f36fcf6432301f280a@sha256:595253274fda59c03c864f038f926467594f503336358aca31b60f5ce45c05dc'
13.03.19 13:28:08 (+0200) Deleted image 'registry2.balena-cloud.com/v2/1ec8f8943bc307f36fcf6432301f280a@sha256:595253274fda59c03c864f038f926467594f503336358aca31b60f5ce45c05dc'
13.03.19 13:28:10 (+0200) Installing service 'main sha256:1cc689e287cde45f857c07c1f6ee2777e3c0a5c8480dc6a99b8bf656227fffe6'
13.03.19 13:28:11 (+0200) Installed service 'main sha256:1cc689e287cde45f857c07c1f6ee2777e3c0a5c8480dc6a99b8bf656227fffe6'
13.03.19 13:28:11 (+0200) Starting service 'main sha256:1cc689e287cde45f857c07c1f6ee2777e3c0a5c8480dc6a99b8bf656227fffe6'
13.03.19 13:28:13 (+0200) Started service 'main sha256:1cc689e287cde45f857c07c1f6ee2777e3c0a5c8480dc6a99b8bf656227fffe6'
13.03.19 13:28:20 (+0200)  main   * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
13.03.19 13:28:48 (+0200)  main  52.4.252.97 - - [13/Mar/2019 11:28:48] "GET / HTTP/1.1" 200 -

# Other information 
- Reported by: Alexandru Costache 

- Test case number: TC49 

- Test run: [https://resinio.testlodge.com/projects/16238/runs/369220?tab=2&run_section_id=539673#executed_case_16132435](https://resinio.testlodge.com/projects/16238/runs/369220?tab=2&run_section_id=539673#executed_case_16132435)

**Comment by acostach** [comment]
Fix in latest release
