### ISSUE TITLE
Provision on supported modems

### ISSUE THREAD

**Issue by balenaio** [balena-os/balena-os#549]
# Description 
Provision device using the supported modems as documented in https://github.com/resin-os/meta-resin/blob/master/README.md#devices-support. If this device is mentioned as a tested platform, FOR EACH modem supported on this platform, run the test steps below.
Please try two SIM cards for this test: A Soracom SIM and another one

# Steps to reproduce issue 
If this device type is not listed in the documentation (https://github.com/resin-os/meta-resin/blob/master/README.md#devices-support) skip this test. Otherwise, continue as it follows.
Download Device OS
Configure the modem connection as documented here: https://docs.resin.io/reference/resinOS/network/2.x/#cellular-modem-setup
Push the following dockerfile.template to the application:
  FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:latest
  CMD ["cat", "/etc/os-release"]

# Expected result 
The device should appear (provision) in the application's dashboard
The device should download and run the application
The logs shown in the dashboard should look similar to the following (watch for the release version, slug/machine and variant fields to be the correct ones for the board you are testing):

06.12.19 08:34:47 (+0200)  main  NAME="Alpine Linux"
06.12.19 08:34:47 (+0200)  main  ID=alpine
06.12.19 08:34:47 (+0200)  main  VERSION_ID=3.8.2
06.12.19 08:34:47 (+0200)  main  PRETTY_NAME="Alpine Linux v3.8"
06.12.19 08:34:47 (+0200)  main  HOME_URL="http://alpinelinux.org"
06.12.19 08:34:47 (+0200)  main  BUG_REPORT_URL="http://bugs.alpinelinux.org"
06.12.19 08:35:00 (+0200)  main  NAME="Alpine Linux"
06.12.19 08:35:00 (+0200)  main  ID=alpine
06.12.19 08:35:00 (+0200)  main  VERSION_ID=3.8.2
06.12.19 08:35:00 (+0200)  main  PRETTY_NAME="Alpine Linux v3.8"
06.12.19 08:35:00 (+0200)  main  HOME_URL="http://alpinelinux.org"
06.12.19 08:35:00 (+0200)  main  BUG_REPORT_URL="http://bugs.alpinelinux.org"

# Actual result 
Not applicable to the NanoPie Neo Air

# Other information 
- Reported by: Vicentiu Galanopulo 

- Test configuration: NanoPi Neo Air 

- Test case number: TC99 

- Test run: [https://resinio.testlodge.com/projects/16238/runs/562636?tab=2&run_suite_id=809935#executed_case_23250660](https://resinio.testlodge.com/projects/16238/runs/562636?tab=2&run_suite_id=809935#executed_case_23250660)

**Comment by vicgal** [comment]
That test should be skipped. Ticket opened by accident.
