### ISSUE TITLE
dbus not installed in python container

### ISSUE THREAD

**Issue by maggie0002** [balena-os/balena-os#552]
I'm using balenalib/%%RESIN_MACHINE_NAME%%-debian-python on an Orange pi Zero. The docs suggest the dbus module is already installed (https://www.balena.io/docs/reference/OS/network/2.x/#changing-the-network-at-runtime), yet in the container being pulled it doesn't appear to be.

**Comment by maggie0002** [comment]
pip install dbus-python generates an error. Turns out `libdbus-glib-1-dev` and `libgirepository1.0-dev` are missing from this container and need installing first.

`install_packages libdbus-glib-1-dev libgirepository1.0-dev`

Then `pip install dbus-python` will work

**Comment by lurch** [comment]
Related to https://github.com/balena-io/docs/issues/1505 ?

**Comment by maggie0002** [comment]
https://github.com/balena-io/docs/issues/1505
